#!/bin/sh
# Installs a `resector` command that runs this checkout's source with Bun, so every
# `git pull` takes effect without a build. Release installs use the release binaries instead.
#   scripts/install-dev.sh [bin-dir]   (default: ~/.local/bin)
set -eu

REPO=$(cd "$(dirname "$0")/.." && pwd)
BIN_DIR=${1:-"$HOME/.local/bin"}

command -v bun >/dev/null || { echo "bun not found on PATH" >&2; exit 1; }
mkdir -p "$BIN_DIR"

cat >"$BIN_DIR/resector" <<EOF
#!/bin/sh
# Generated by $REPO/scripts/install-dev.sh; runs that checkout's source.
REPO='$REPO'
# Refresh dependencies when bun.lock changed since the last install (e.g. after a pull).
STAMP="\$REPO/node_modules/.install-dev-stamp"
if [ ! -e "\$STAMP" ] || [ "\$REPO/bun.lock" -nt "\$STAMP" ]; then
  (cd "\$REPO" && bun install --frozen-lockfile >&2 && touch "\$STAMP") || exit 1
fi
# The checkout's bunfig.toml preloads the Solid JSX runtime; Bun would otherwise read the
# bunfig.toml of the current directory. Like the release binary, ignore the project's .env.
exec bun --config="\$REPO/bunfig.toml" --no-env-file "\$REPO/src/main.ts" "\$@"
EOF
chmod 755 "$BIN_DIR/resector"

echo "installed $BIN_DIR/resector -> $REPO"
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "note: $BIN_DIR is not on PATH; add it to your shell profile" >&2 ;;
esac
