import { expect, test } from 'bun:test';
import { TARGETS, assetName, parseChecksums, renderFormula, versionFromTag } from './release';

test('targets are the four NFR-5 platforms', () => {
  expect(TARGETS).toEqual(['darwin-arm64', 'darwin-x64', 'linux-x64', 'linux-arm64']);
});

test('a tag matching the package version yields the version', () => {
  expect(versionFromTag('v1.2.3', '1.2.3')).toBe('1.2.3');
});

test('a tag without the v prefix is rejected', () => {
  expect(() => versionFromTag('1.2.3', '1.2.3')).toThrow('tag "1.2.3" must look like v<version>');
});

test('a tag that disagrees with package.json is rejected', () => {
  expect(() => versionFromTag('v1.2.4', '1.2.3'))
    .toThrow('tag v1.2.4 does not match package.json version 1.2.3');
});

test('asset names carry version and target', () => {
  expect(assetName('1.2.3', 'darwin-arm64')).toBe('resector-v1.2.3-darwin-arm64.tar.gz');
});

test('checksums parse from sha256sum output, text and binary mode', () => {
  const text = 'aaa  resector-v1-linux-x64.tar.gz\nbbb *resector-v1-darwin-arm64.tar.gz\n\n';
  expect(parseChecksums(text)).toEqual(new Map([
    ['resector-v1-linux-x64.tar.gz', 'aaa'],
    ['resector-v1-darwin-arm64.tar.gz', 'bbb'],
  ]));
});

test('a malformed checksum line is rejected', () => {
  expect(() => parseChecksums('nonsense\n')).toThrow('malformed checksum line: "nonsense"');
});

const sums = new Map(TARGETS.map(t => [assetName('1.2.3', t), `sha-${t}`]));

test('the formula pins every target to its release asset and checksum', () => {
  expect(renderFormula({ version: '1.2.3', repo: 'artkoenig/resector', checksums: sums })).toBe(`\
# Generated by scripts/formula.ts for resector v1.2.3. Do not edit by hand.
class Resector < Formula
  desc "Coding agent harness for local LLMs with small context windows"
  homepage "https://github.com/artkoenig/resector"
  version "1.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/artkoenig/resector/releases/download/v1.2.3/resector-v1.2.3-darwin-arm64.tar.gz"
      sha256 "sha-darwin-arm64"
    end
    on_intel do
      url "https://github.com/artkoenig/resector/releases/download/v1.2.3/resector-v1.2.3-darwin-x64.tar.gz"
      sha256 "sha-darwin-x64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/artkoenig/resector/releases/download/v1.2.3/resector-v1.2.3-linux-arm64.tar.gz"
      sha256 "sha-linux-arm64"
    end
    on_intel do
      url "https://github.com/artkoenig/resector/releases/download/v1.2.3/resector-v1.2.3-linux-x64.tar.gz"
      sha256 "sha-linux-x64"
    end
  end

  def install
    bin.install "resector"
  end

  test do
    assert_equal "resector 1.2.3", shell_output("#{bin}/resector --version").strip
  end
end
`);
});

test('the formula refuses to render with a missing checksum', () => {
  const partial = new Map(sums);
  partial.delete(assetName('1.2.3', 'linux-arm64'));
  expect(() => renderFormula({ version: '1.2.3', repo: 'artkoenig/resector', checksums: partial }))
    .toThrow('no checksum for resector-v1.2.3-linux-arm64.tar.gz');
});
