// Release helpers (NFR-5): compile targets, asset naming, checksums, Homebrew formula.
// Pure; scripts/build.ts and scripts/formula.ts do the I/O.

export const TARGETS = ['darwin-arm64', 'darwin-x64', 'linux-x64', 'linux-arm64'] as const;
export type Target = (typeof TARGETS)[number];

export function versionFromTag(tag: string, pkgVersion: string): string {
  if (!tag.startsWith('v')) throw new Error(`tag "${tag}" must look like v<version>`);
  if (tag.slice(1) !== pkgVersion)
    throw new Error(`tag ${tag} does not match package.json version ${pkgVersion}`);
  return pkgVersion;
}

export const assetName = (version: string, target: Target) =>
  `resector-v${version}-${target}.tar.gz`;

// `sha256sum` / `shasum -a 256` output: "<hash>  <file>" or "<hash> *<file>".
export function parseChecksums(text: string): Map<string, string> {
  const sums = new Map<string, string>();
  for (const line of text.split('\n').filter(l => l.trim())) {
    const m = /^([0-9a-z-]+) [ *](.+)$/.exec(line);
    if (!m) throw new Error(`malformed checksum line: "${line}"`);
    sums.set(m[2]!, m[1]!);
  }
  return sums;
}

type FormulaInput = { version: string; repo: string; checksums: Map<string, string> };

export function renderFormula({ version, repo, checksums }: FormulaInput): string {
  const asset = (target: Target) => {
    const name = assetName(version, target);
    const sha = checksums.get(name);
    if (!sha) throw new Error(`no checksum for ${name}`);
    return `      url "https://github.com/${repo}/releases/download/v${version}/${name}"\n` +
      `      sha256 "${sha}"\n`;
  };
  const os = (block: string, platform: 'darwin' | 'linux') =>
    `  ${block} do\n` +
    `    on_arm do\n${asset(`${platform}-arm64`)}    end\n` +
    `    on_intel do\n${asset(`${platform}-x64`)}    end\n` +
    `  end\n`;
  return `\
# Generated by scripts/formula.ts for resector v${version}. Do not edit by hand.
class Resector < Formula
  desc "Coding agent harness for local LLMs with small context windows"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

${os('on_macos', 'darwin')}
${os('on_linux', 'linux')}
  def install
    bin.install "resector"
  end

  test do
    assert_equal "resector ${version}", shell_output("#{bin}/resector --version").strip
  end
end
`;
}
